server:
  port: 9090
  servlet:
    context-path: /zimo
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  #指定引擎依赖
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC #指定数据库地址
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml  #指定mapper文件的目录
  type-aliases-package: boot.domain #指定实体类包
  configuration:
    map-underscore-to-camel-case: true #启用驼峰命名法